### ISSUE TITLE
Why GPL license?

### ISSUE THREAD

**Issue by thomasf** [vwt-digital/jwkaas#13]
this means that no one can use this library in a commercial products without having to open source the whole project due to the linking clause of the GPL. This license limits for which projects this library can be used a lot. LGPL is commonly more suited for libraries for this reason.

**Comment by MaxvanderWeide** [comment]
Hi Thomas,

Thanks for the question! 
A lot of the open source projects that we use require that the using party also inherits the same license for their project. Next to that requirement, we also believe that working with an open source will strengthen the entire community and will help create more projects like this one!

For more information, [check the license for this specific project](https://github.com/vwt-digital/jwkaas/blob/master/LICENSE).

**Comment by thomasf** [comment]
> For more information, check the license for this specific project.

 Yes I know the GPL very well.

LGPL is also an GPL open source license, the only difference is the omitting of the linking clause. If you own the copyright for this code you can even dual license it under how many licenses if you want regardless of what the other projects licenses you use say. 

As you might know GPL is especially problematic for libraries.

Anyways, I won't bother you any more with this. It's just a shame that using GPL instead of LGPL makes this project useless for a lot of potential users.
