### ISSUE TITLE
Syntax Error in warning log for expired token.

### ISSUE THREAD

**Issue by mayankagarwal2402** [vwt-digital/jwkaas#3]
[PR with fix](https://github.com/vwt-digital/jwkaas/pull/2)

**Comment by hbvanveen-vwt** [comment]
Thank you for bringing up this issue. Sorry for our late response.
However, JWKaas does not support Python 2, where the f-string (https://realpython.com/python-f-strings/) is reported as a syntax error.
Next to that, the change you propose also changes the functionality of the logged message as the JWKaas.JWK_ALLOWED_ALGORITHMS would not be evaluated anymore, but taken as a literal.
